#!/usr/bin/env bash
# install / conffigure HAProxy on lb-01

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 484035-web-01 52.91.147.124:80 check
        server 484035-web-02 107.21.183.54:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy / init-script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing for errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
