#!/usr/bin/env bash
# FizzBuzz
x=1
while [ $x -lt 101 ]
do
    if [ $((x%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((x%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((x%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$x"
    fi
    let x+=1
done
