#!/usr/bin/env bash
# Superstitious numbers
x=1
while [ $x -le 20 ]
do
	if [ $x -eq 4 ]; then
		echo $x
		echo "bad luck from China"
	elif [ $x -eq 9 ]; then
		echo $x
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]; then
		echo $x
		echo "bad luck from Italy"
	else
		echo $x
	fi
	((x++))
done
